# Yarn configuration file
# This ensures yarn is used consistently across the project

# Enable Yarn Berry (modern yarn) features
nodeLinker: node-modules

# Set the package manager to yarn
packageManager: "1.22.22"

# Enable zero-installs for better performance
enableGlobalCache: true

# Set the registry to npm
npmRegistryServer: "https://registry.npmjs.org"

# Enable PnP (Plug'n'Play) for better dependency resolution
# pnpMode: loose

# Configure network settings
networkConcurrency: 8

# Enable immutable installs
enableImmutableInstalls: true
