# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: envio-indexer
networks:
  - id: 10143
    start_block: 0
    contracts:
      - name: Chog
        address:
          - 0xE0590015A873bF326bd645c3E1266d4db41C4E6B
        handler: src/EventHandlers.ts
        events:
          - event: Transfer(address indexed from, address indexed to, uint256 value)
field_selection:
  transaction_fields:
    - "hash"
